### ISSUE TITLE
blrec把文件转换为mp4后,自动上传出现错误

### ISSUE THREAD

**Issue by q513902026** [qqyuanxinqq/AutoUpload_Blrec#1]
blrec版本:2.0.0b3
问题概述:
VideoPostprocessingCompletedEvent事件的data.path是最终的文件名称,可能与VideoFileCreatedEvent事件的data.path名称不一致,从而导致错误

```
{
  "id": "5a288b3e-d963-11ee-afe5-80fa5b90654e",
  "date": "2024-03-03 21:38:43.266028+08:00",
  "type": "VideoFileCompletedEvent",
  "data": {
    "room_id": 1163043,
    "path": "D:\\repo\\record\\AutoUpload_Blrec\\Videos\\1163043\\1163043_20240303-21-34-00.flv"
  }
}
```

```
{
  "id": "5bcfecf6-d963-11ee-a1af-80fa5b90654e",
  "date": "2024-03-03 21:38:46.040703+08:00",
  "type": "VideoPostprocessingCompletedEvent",
  "data": {
    "room_id": 1163043,
    "path": "D:\\repo\\record\\AutoUpload_Blrec\\Videos\\1163043\\1163043_20240303-21-34-00.mp4"
  }
}
```

目前会导致以下错误

```
ERROR:root:'D:\\repo\\record\\AutoUpload_Blrec\\Videos\\1163043\\1163043_20240303-21-34-00.mp4'
Traceback (most recent call last):
  File "D:\repo\record\AutoUpload_Blrec\src\httpserver.py", line 43, in do_POST
    self.handle_event(event)
  File "D:\repo\record\AutoUpload_Blrec\src\httpserver.py", line 84, in handle_event
    MyHandler.handle_video_file_completed(event)
  File "D:\repo\record\AutoUpload_Blrec\src\httpserver.py", line 176, in handle_video_file_completed
    list_file = cls.videos_active.pop(filename)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'D:\\repo\\record\\AutoUpload_Blrec\\Videos\\1163043\\1163043_20240303-21-34-00.mp4'

```

以下是_list中1163043_20240303_21-33-50.json存储的数据
```
{
    "version": "v1",
    "room_id": "1163043",
    "time": "2024-03-03 21:33:50.376307+08:00",
    "year": "2024",
    "month": "03",
    "day": "03",
    "hour": "21",
    "minute": "33",
    "second": "50",
    "live_title": "\u9e7f\u5934\u597d\u83dc\u5c0f\u9152\u9986",
    "live_title_now": "\u9e7f\u5934\u597d\u83dc\u5c0f\u9152\u9986",
    "status": "Living",
    "is_uploaded": false,
    "video_list": [],
    "video_list_now": {
        "D:\\repo\\record\\AutoUpload_Blrec\\Videos\\1163043\\1163043_20240303-21-34-00.flv": {
            "start_time": "2024-03-03 21:34:00.593055+08:00",
            "filename": "D:\\repo\\record\\AutoUpload_Blrec\\Videos\\1163043\\1163043_20240303-21-34-00.flv",
            "live_title": "\u9e7f\u5934\u597d\u83dc\u5c0f\u9152\u9986"
        },
        "D:\\repo\\record\\AutoUpload_Blrec\\Videos\\1163043\\1163043_20240303-21-38-43.flv": {
            "start_time": "2024-03-03 21:38:43.549385+08:00",
            "filename": "D:\\repo\\record\\AutoUpload_Blrec\\Videos\\1163043\\1163043_20240303-21-38-43.flv",
            "live_title": "\u9e7f\u5934\u597d\u83dc\u5c0f\u9152\u9986"
        }
    }
}
```

**Comment by qqyuanxinqq** [comment]
感谢你细致的问题描述，这个bug现在应该修复了。
（抱歉之前没看到…这个小bug拖了有些时间…

**Comment by qqyuanxinqq** [comment]
感谢你细致的问题描述，这个bug现在应该修复了。
（抱歉之前没看到…这个小bug拖了有些时间…
